List<String> symbol = [
  'ancient.png',
  'awareness.png',
  'dreams.png',
  'focus.png',
  'forest.png',
  'harmony.png',
  'healing.png',
  'hills.png',
  'inspiration.png',
  'journey.png',
  'meditation.png',
  'mindfulness.png',
  'relaxing.png',
  'serenity.png',
  'siesta.png',
  'sleep.png',
  'solitude.png',
  'symphony.png',
  'wilderness.png',
  'zen.png',
  'ancient.png',
  'awareness.png',
  'dreams.png',
  'focus.png',
  'forest.png',
  'harmony.png',
  'healing.png',
  'hills.png',
  'inspiration.png',
  'journey.png',
  'meditation.png',
  'mindfulness.png',
  'relaxing.png',
  'serenity.png',
  'siesta.png',
  'sleep.png',
  'solitude.png',
  'symphony.png',
  'wilderness.png',
  'zen.png',
  'ancient.png',
  'awareness.png',
  'dreams.png',
  'focus.png',
  'forest.png',
];

List<String> buddhaImg = [
  'buddha1.svg',
  'buddha2.svg',
  'buddha3.svg',
  'buddha4.svg',
  'buddha5.svg',
  'buddha6.svg',
  'buddha7.svg',
  'buddha8.svg',
  'buddha9.svg',
  'buddha10.svg',
  'buddha11.svg',
  'buddha12.svg',
  'buddha13.svg',
  'buddha14.svg',
  'buddha15.svg',
  'buddha16.svg',
  'buddha17.svg',
  'buddha18.svg',
  'buddha19.svg',
  'buddha20.svg',
  'buddha21.svg',
  'buddha22.svg',
  'buddha23.svg',
  'buddha24.svg',
  'buddha1.svg',
  'buddha2.svg',
  'buddha3.svg',
  'buddha4.svg',
  'buddha5.svg',
  'buddha6.svg',
  'buddha7.svg',
  'buddha8.svg',
  'buddha9.svg',
  'buddha10.svg',
  'buddha11.svg',
  'buddha12.svg',
  'buddha13.svg',
  'buddha14.svg',
  'buddha15.svg',
  'buddha16.svg',
  'buddha17.svg',
  'buddha18.svg',
  'buddha19.svg',
  'buddha20.svg',
  'buddha24.svg',
];

List<String> notiImg = [
  'buddha1.png',
  'buddha2.png',
  'buddha3.png',
  'buddha4.png',
  'buddha5.png',
  'buddha6.png',
  'buddha7.png',
  'buddha8.png',
  'buddha9.png',
  'buddha10.png',
  'buddha11.png',
  'buddha12.png',
  'buddha13.png',
  'buddha14.png',
  'buddha15.png',
  'buddha16.png',
  'buddha17.png',
  'buddha18.png',
  'buddha19.png',
  'buddha20.png',
  'buddha21.png',
  'buddha22.png',
  'buddha23.png',
  'buddha24.png',
  'buddha1.png',
  'buddha2.png',
  'buddha3.png',
  'buddha4.png',
  'buddha5.png',
  'buddha6.png',
  'buddha7.png',
  'buddha8.png',
  'buddha9.png',
  'buddha10.png',
  'buddha11.png',
  'buddha12.png',
  'buddha13.png',
  'buddha14.png',
  'buddha15.png',
  'buddha16.png',
  'buddha17.png',
  'buddha18.png',
  'buddha19.png',
  'buddha20.png',
  'buddha24.png',
];

List<String> allImages = [
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
];

List<String> allSongs = [
  'assets/moods/ancient.mp3',
  'assets/moods/sleep_mood.mp3',
  'assets/moods/dreams.mp3',
  'assets/moods/zen_mood.mp3',
  'assets/moods/journey.mp3',
  'assets/moods/harmony.mp3',
  'assets/moods/birds.mp3',
  'assets/moods/meditation_mood_ohm.mp3',
  'assets/moods/siesta.mp3',
  'assets/moods/sleep_mood.mp3',
  'assets/moods/serenity.mp3',
  'assets/moods/hills_mood.mp3',
  'assets/moods/ancient.mp3',
  'assets/moods/solitude.mp3',
  'assets/moods/forest_mood.mp3',
  'assets/moods/serenity.mp3',
  'assets/moods/mindfulness_mood.mp3',
  'assets/moods/awareness.mp3',
  'assets/moods/inspiration_mood.mp3',
  'assets/moods/sleep_mood.mp3',
  'assets/moods/hills_mood.mp3',
  'assets/moods/forest_mood.mp3',
  'assets/moods/relaxing_mood.mp3',
  'assets/moods/romantic_mood.mp3',
  'assets/moods/siesta.mp3',
  'assets/moods/wilderness.mp3',
  'assets/moods/journey.mp3',
  'assets/moods/wilderness.mp3',
  'assets/moods/sleep_mood.mp3',
  'assets/moods/sleep_mood.mp3',
  'assets/moods/hills_mood.mp3',
  'assets/moods/birds.mp3',
  'assets/moods/journey.mp3',
  'assets/moods/romantic_mood.mp3',
  'assets/moods/awareness.mp3',
  'assets/moods/zen_mood.mp3',
  'assets/moods/ancient.mp3',
  'assets/moods/sleep_mood.mp3',
  'assets/moods/dreams.mp3',
  'assets/moods/zen_mood.mp3',
  'assets/moods/journey.mp3',
  'assets/moods/ancient.mp3',
  'assets/moods/sleep_mood.mp3',
  'assets/moods/dreams.mp3',
  'assets/moods/zen_mood.mp3',
];

List<String> songName = [
  "Calm",
  "De-Stress",
  "Zen",
  "Journey",
  "Harmony",
  "Bliss",
  "Gratitude",
  "Office",
  "Sleep",
  "Sunrise In Japan",
  "Hills",
  "Ancient",
  "Solitude",
  "Voyage",
  "Serenity",
  "Pacafic",
  "Dreams",
  "Calm Waters",
  "Euphoria",
  "Deep Sleep",
  "Evening Rain",
  "Peace",
  "Yesterday",
  "Urban Traffic",
  "Spiritual",
  "Space",
  "Grace",
  "Wilderness",
  "Gentle Sleep",
  "Sweet Sleep",
  "Sunset",
  "Forest path",
  "Om-Aum",
  "Unwind",
  "Riverside",
  "Nostalgic",
  "Awareness",
  "Let Go",
  "Cosmic",
  "Loving Kindness",
  "Mindfulness",
  "Relaxing",
  "Healing",
  "Inspiration",
  "Meditation"
];

List<String> zenImages = [
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
];

List<String> zenSong = [
  'assets/moods/zen_mood.mp3',
  'assets/moods/hills_mood.mp3',
  'assets/moods/relaxing_mood.mp3',
  'assets/moods/serenity.mp3',
  'assets/moods/symphony.mp3',
  'assets/moods/meditation_mood_ohm.mp3',
  'assets/moods/awareness.mp3',
  'assets/moods/dreams.mp3',
  'assets/moods/mindfulness_mood.mp3',
  'assets/moods/meditation_mood_ohm.mp3',
];

List<String> zenName = [
  "Zen",
  "Gratitude",
  "Sunrise In Japan",
  "Serenity",
  "Spiritual",
  "Om-Aum",
  "Awareness",
  "Let Go",
  "Loving Kindness",
  "Mindfulness",
  "Meditation"
];

List<String> moodImages = [
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
];

List<String> moodSong = [
  'assets/moods/journey.mp3',
  'assets/moods/sleep_mood.mp3',
  'assets/moods/solitude.mp3',
  'assets/moods/serenity.mp3',
  'assets/moods/dreams.mp3',
  'assets/moods/meditation_mood_ohm.mp3',
  'assets/moods/sleep_mood.mp3',
  'assets/moods/dreams.mp3',
  'assets/moods/mindfulness_mood.mp3',
  'assets/moods/meditation_mood_ohm.mp3',
  'assets/moods/solitude.mp3',
  'assets/moods/serenity.mp3',
];

List<String> moodName = [
  "Journey",
  "Sleep",
  "Solitude",
  "Voyage",
  "Dreams",
  "Euphoria",
  "Deep Sleep",
  "Yesterday",
  "Gentle Sleep",
  "Sweet Sleep",
  "Nostalgic",
  "Inspiration"
];

List<String> ambientImages = [
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
];

List<String> ambientSong = [
  'assets/moods/harmony.mp3',
  'assets/moods/hills_mood.mp3',
  'assets/moods/ancient.mp3',
  'assets/moods/wilderness.mp3',
  'assets/moods/symphony.mp3',
  'assets/moods/journey.mp3',
  'assets/moods/forest_mood.mp3',
  'assets/moods/birds.mp3',
  'assets/moods/wilderness.mp3',
  'assets/moods/forest_mood.mp3',
  'assets/moods/zen_mood.mp3',
];

List<String> ambientName = [
  "Office",
  "Hills",
  "Ancient",
  "Pacific",
  "Calm Waters",
  "Evening Rain",
  "Urban Traffic",
  "Space",
  "Wilderness",
  "Forest path",
  "Riverside",
];

List<String> relaxImages = [
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
  'assets/images/group.png',
  'assets/images/mask_group.png',
];

List<String> relaxSong = [
  'assets/moods/insiration_mood.mp3',
  'assets/moods/harmony.mp3',
  'assets/moods/birds.mp3',
  'assets/moods/hills_mood.mp3',
  'assets/moods/serenity.mp3',
  'assets/moods/romantic_mood.mp3',
  'assets/moods/relaxing_mood.mp3',
  'assets/moods/hills_mood.mp3',
];

List<String> relaxName = [
  "De-Stress",
  "Harmony",
  "Bliss",
  "Peace",
  "Unwind",
  "Cosmic",
  "Relaxing",
  "Healing",
];

List<String> byteSong = [
  'wind.mp3',
  'chimes.mp3',
  'bell.mp3',
  'thunder.mp3',
  'drone.mp3',
  'river.mp3',
  'wave.mp3',
  'piano.mp3',
  'seagull.mp3',
  'bowl.mp3',
  'cat.mp3',
  'chant.mp3',
  'guitar.mp3',
  'aircon.mp3',
  'bubble.mp3',
  'cricket.mp3',
  'drone_old.mp3',
  'fire.mp3',
  'drone.mp3',
  'cat.mp3'
];

List<String> byteSongName = [
  "Light Wind",
  "Chimes",
  "Bells",
  "Thunder",
  "Meadow",
  "Mountain River",
  "Birds",
  "River",
  "Sea waves",
  "Piano",
  "Seagulls",
  "Bowl",
  "Cat Puri",
  "Chant",
  "Guitar",
  "Aircon",
  "Bubbles",
  "Bonfire",
  "Breathing",
  "Fan"
];
